---
title: "Veteran Crisisline 2014"
author: "Mihir Iyer"
date: "April 14, 2016"
output: 
  html_document:
    toc: true
    toc_float: true
---


```{r dataload}
knitr::opts_chunk$set(cache = TRUE)
#load jsonlite library to read json file
library(jsonlite)
#read the file and assign to crisis
crisis <- fromJSON("~/Rprojects/Crisis/VeteransCrisisLineFY14FOIA1500242.json")
```


# Introduction to the VA Crisis Line data

On April 14th 2016, VA made available a [collection of record-level and aggregate Veterans Crisis Line call data](http://catalog.data.gov/dataset/veterans-crisis-line-call-record-level-data). The data was made available through a Freedom of Information Act (FOIA) Request 15-00242-F appeal. This [collection consists of five data sets](http://catalog.data.gov/dataset?collection_package_id=e7f77f49-9d23-45bb-bb52-6b5ac99189db). 




```{r dataprep}

#select NON-REDACTED variables

crisis.nred <- crisis[, c(4,5,6,7,8,10,11,16,37,47,49,50,61,63,64,65,68)]

#load chron library to convert CALL_Duration field into a time only (no date) object
library(chron)

crisis$CALL_DURATION <- times(crisis$CALL_DURATION)

```

